### PR TITLE
Fix older ruby version requirement

### PR DESCRIPTION
**Pull request by ahaverty**

### CODE REVIEW

**Comment by gabe-ochoa** [comment]
Lgtm! Thanks for the clean up and fix :)

**Comment by gabe-ochoa** [comment]
I realized I never set up CI and and auto publish workflow for this gem. I won't have time to do this until next week but should be able to push up a new version before Friday.

**Comment by ahaverty** [comment]
I actually only tested vie rspec before PR'ing. I didn't realise the api has changed so much in the last year, so I've moved to using some once off httparty calls for now.
Thanks for responding 👍

**Comment by gabe-ochoa** [comment]
No problem - thanks for the PR. 

I really should give this library an update now that the commerce v1 Squarespace APIs have been released. Not sure when the old ones will be deprecated.

**Pull request merged**
